# Generated by Django 5.0.2 on 2024-03-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_compra_itemdacompra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quantidade',
            new_name='estoque',
        ),
    ]
