# Generated by Django 5.0.2 on 2024-03-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_carrinho_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='qtdItens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
