# Generated by Django 5.0.2 on 2024-03-04 23:52

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_compra_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdocarrinho',
            name='quantidade',
            field=models.IntegerField(validators=[api.validators.IsPositive]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(validators=[api.validators.IsPositive]),
        ),
    ]
